export {
  CAPABILITIES,
  PERMISSIONS,
  ROLE_ALIASES,
  ROLE_REGISTRY,
  ROLES,
  VALID_ROLES,
  getPrimaryRole,
  getRoleCapabilities,
  getRoleDiagnostics,
  getRolePermissions,
  getUnknownRoles,
  getUserRoles,
  hasCapability,
  hasPermission,
  hasRole,
  isRoleWithinRolloutStage,
  normalizeRole,
} from '../server-shared/role-engine.js';
