// Все задания приложения АПГ
// check(keys, favsCount, referralCount) — условие выполнения
// progress(keys, favsCount, referralCount) — текущее значение для прогресс-бара
// total — нужно для прогресс-бара

export const TASKS = [
  {
    id:       'first_open',
    emoji:    '🎯',
    title:    'Добро пожаловать',
    desc:     'Впервые открой приложение АПГ',
    reward:   1,
    check:    () => true,
    total:    null,
    progress: null,
  },
  {
    id:       'visit_3',
    emoji:    '🗝️',
    title:    'Первые шаги',
    desc:     'Посети 3 партнёра АПГ',
    reward:   2,
    check:    (k) => k >= 3,
    total:    3,
    progress: (k) => Math.min(k, 3),
  },
  {
    id:       'visit_10',
    emoji:    '🔥',
    title:    'Завсегдатай',
    desc:     'Посети 10 партнёров',
    reward:   5,
    check:    (k) => k >= 10,
    total:    10,
    progress: (k) => Math.min(k, 10),
  },
  {
    id:       'visit_25',
    emoji:    '💎',
    title:    'Преданный участник',
    desc:     'Посети 25 партнёров',
    reward:   10,
    check:    (k) => k >= 25,
    total:    25,
    progress: (k) => Math.min(k, 25),
  },
  {
    id:       'fav_3',
    emoji:    '⭐',
    title:    'Знаток города',
    desc:     'Добавь 3 заведения в избранное',
    reward:   2,
    check:    (k, f) => f >= 3,
    total:    3,
    progress: (k, f) => Math.min(f, 3),
  },
  {
    id:       'fav_5',
    emoji:    '❤️',
    title:    'Свой человек',
    desc:     'Добавь 5 заведений в избранное',
    reward:   3,
    check:    (k, f) => f >= 5,
    total:    5,
    progress: (k, f) => Math.min(f, 5),
  },
  {
    id:       'referral_1',
    emoji:    '👥',
    title:    'Амбассадор',
    desc:     'Пригласи 1 друга',
    reward:   3,
    check:    (k, f, r) => r >= 1,
    total:    1,
    progress: (k, f, r) => Math.min(r, 1),
  },
  {
    id:       'referral_3',
    emoji:    '🌟',
    title:    'Народный лидер',
    desc:     'Пригласи 3 друзей',
    reward:   8,
    check:    (k, f, r) => r >= 3,
    total:    3,
    progress: (k, f, r) => Math.min(r, 3),
  },
];
