// check(keys, favCount, referralCount, streak, scannedCount)
// sc = scannedCount — количество уникальных посещённых партнёров

export const TASKS = [
  {
    id: 'first_open',
    emoji: '🎯', title: 'Добро пожаловать',
    desc: 'Впервые открой приложение АПГ',
    reward: 1,
    check: () => true, total: null, progress: null,
  },
  {
    id: 'fav_1',
    emoji: '💙', title: 'Первое любимое место',
    desc: 'Добавь заведение в избранное',
    reward: 1,
    check: (k, f) => f >= 1, total: 1, progress: (k, f) => Math.min(f, 1),
  },
  {
    id: 'visit_3',
    emoji: '🗝️', title: 'Первые шаги',
    desc: 'Посети 3 партнёра АПГ',
    reward: 2,
    check: (k, f, r, s, sc) => sc >= 3, total: 3, progress: (k, f, r, s, sc) => Math.min(sc, 3),
  },
  {
    id: 'fav_3',
    emoji: '⭐', title: 'Знаток города',
    desc: 'Добавь 3 заведения в избранное',
    reward: 2,
    check: (k, f) => f >= 3, total: 3, progress: (k, f) => Math.min(f, 3),
  },
  {
    id: 'visit_10',
    emoji: '🔥', title: 'Завсегдатай',
    desc: 'Посети 10 партнёров',
    reward: 5,
    check: (k, f, r, s, sc) => sc >= 10, total: 10, progress: (k, f, r, s, sc) => Math.min(sc, 10),
  },
  {
    id: 'keys_15',
    emoji: '🔑', title: 'Знаток Зеленограда',
    desc: 'Собери 15 ключей',
    reward: 5,
    check: (k) => k >= 15, total: 15, progress: (k) => Math.min(k, 15),
  },
  {
    id: 'fav_5',
    emoji: '❤️', title: 'Свой человек',
    desc: 'Добавь 5 заведений в избранное',
    reward: 3,
    check: (k, f) => f >= 5, total: 5, progress: (k, f) => Math.min(f, 5),
  },
  {
    id: 'referral_1',
    emoji: '👥', title: 'Амбассадор',
    desc: 'Пригласи 1 друга',
    reward: 3,
    check: (k, f, r) => r >= 1, total: 1, progress: (k, f, r) => Math.min(r, 1),
  },
  {
    id: 'visit_25',
    emoji: '💎', title: 'Преданный участник',
    desc: 'Посети 25 партнёров',
    reward: 10,
    check: (k, f, r, s, sc) => sc >= 25, total: 25, progress: (k, f, r, s, sc) => Math.min(sc, 25),
  },
  {
    id: 'fav_10',
    emoji: '🏅', title: 'Коллекционер мест',
    desc: 'Добавь 10 заведений в избранное',
    reward: 8,
    check: (k, f) => f >= 10, total: 10, progress: (k, f) => Math.min(f, 10),
  },
  {
    id: 'referral_3',
    emoji: '🌟', title: 'Народный лидер',
    desc: 'Пригласи 3 друзей',
    reward: 8,
    check: (k, f, r) => r >= 3, total: 3, progress: (k, f, r) => Math.min(r, 3),
  },
  {
    id: 'visit_50',
    emoji: '🏆', title: 'Постоянный гость',
    desc: 'Посети партнёров 50 раз',
    reward: 15,
    check: (k) => k >= 50, total: 50, progress: (k) => Math.min(k, 50),
  },
  {
    id: 'referral_5',
    emoji: '🚀', title: 'Звезда АПГ',
    desc: 'Пригласи 5 друзей',
    reward: 15,
    check: (k, f, r) => r >= 5, total: 5, progress: (k, f, r) => Math.min(r, 5),
  },
  {
    id: 'visit_100',
    emoji: '👑', title: 'Легенда Зеленограда',
    desc: 'Набери 100 ключей — настоящая легенда!',
    reward: 30,
    check: (k) => k >= 100, total: 100, progress: (k) => Math.min(k, 100),
  },
  {
    id: 'streak_3',
    emoji: '🔥', title: 'В огне',
    desc: 'Посещай партнёров 3 дня подряд',
    reward: 5,
    check: (k, f, r, s) => s >= 3, total: 3, progress: (k, f, r, s) => Math.min(s, 3),
  },
  {
    id: 'streak_7',
    emoji: '⚡', title: 'Неостановимый',
    desc: 'Не прерывай серию 7 дней подряд',
    reward: 12,
    check: (k, f, r, s) => s >= 7, total: 7, progress: (k, f, r, s) => Math.min(s, 7),
  },
  {
    id: 'streak_30',
    emoji: '💫', title: 'Месяц активности',
    desc: '30 дней подряд — настоящий фанат АПГ!',
    reward: 40,
    check: (k, f, r, s) => s >= 30, total: 30, progress: (k, f, r, s) => Math.min(s, 30),
  },
];
